### ISSUE TITLE
最後に入力した文字列のバス停予測が隣の入力欄でも反映される

### ISSUE THREAD

**Issue by takachan-mirai** [i544c/fuck-the-h4k0bu5-v2#1]
こんな感じ
<img width="960" alt="default" src="https://user-images.githubusercontent.com/22951237/37874102-d4ea012c-3062-11e8-8aa6-40f07cbd5f05.png">

**Comment by i544c** [comment]
コードが冗長になるし，面倒だからやらなかったの．．．
やっぱりユーザ的には使いづらいよね，直すわ
