### ISSUE TITLE
予測バス停候補が表示される前にfocusを変えると、予測リストが表示されたままになる

### ISSUE THREAD

**Issue by b4h0-c4t** [i544c/fuck-the-h4k0bu5-v2#3]
focusイベントにリストを閉じる関数替わり当たっていて、先にunfocusしちゃうと発火しなくなるとかそんなんだと思います。

**Comment by i544c** [comment]
これはなかなかめんどいな
そもそも[使ってるコンポーネント](https://ant.design/components/auto-complete/)のバグなんだろうけど，どうにかできなくもないか．．．
